### ISSUE TITLE
TASK [../roles/mapr-configure-security-fetch-keys : Copy keys to local] 

### ISSUE THREAD

**Issue by brazzaville** [mapr-emea/mapr-ansible#28]
from sites/mapr-core.yml 
 - name: Fetch keys, when no CLDB change happened
    hosts: mapr-cldb[0]
    roles:
     - {role: ../roles/mapr-configure-security-fetch-keys,
        when: mapr_security != 'none' and (cldb_changes|int) == 0}

And we have in role: ../roles/mapr-configure-security-fetch-keys, this stuff :+1: 
- name: Copy keys to local
  fetch: src=/opt/mapr/conf/{{ item }} dest=/tmp/{{ item }} flat=yes
  with_items:
     - maprserverticket
     - cldb.key
     - ssl_keystore
     - ssl_truststore

Then generate an error 

TASK [../roles/mapr-configure-security-fetch-keys : Copy keys to local] *****************************************************************************************************
failed: [192.168.2.60] (item=maprserverticket) => {"changed": false, "item": "maprserverticket", "msg": "file not found: /opt/mapr/conf/maprserverticket"}
failed: [192.168.2.60] (item=cldb.key) => {"changed": false, "item": "cldb.key", "msg": "file not found: /opt/mapr/conf/cldb.key"}
failed: [192.168.2.60] (item=ssl_keystore) => {"changed": false, "item": "ssl_keystore", "msg": "file not found: /opt/mapr/conf/ssl_keystore"}
failed: [192.168.2.60] (item=ssl_truststore) => {"changed": false, "item": "ssl_truststore", "msg": "file not found: /opt/mapr/conf/ssl_truststore"}

Cheers

**Comment by devproof** [comment]
Are you setting up a cluster with security?
Are you running the script a second time?

Please send me a private message with the group_vars/all configuration or post it here and remove sensitive stuff.

**Comment by kieucuong** [comment]
I faced the same error when setting up a cluster without security (`security_all: none` in `group_vars/all`) configuration. 
I made a temporary fix by moving 
```
- name: Copy keys to local
  fetch: src=/opt/mapr/conf/{{ item }} dest=/tmp/{{ item }} flat=yes
  with_items:
  - ssl_truststore
  - mapruserticket
  when: inventory_hostname == groups["mapr-cldb"][0]
```
to a new role (for example `mapr-client-configure-fetch-key`) and modify `site-client.yml` as well
```
- name: Fetch files from cluster required for client
  hosts: mapr-cldb[0]
  roles:
    - {role: mapr-client-configure-fetch-key, when: mapr_security != 'none'}
    - mapr-client-configure-nativesecurity-fetch
```
Hope to see the official fix soon.
Thanks a lot.
